### PR TITLE
Fixed chainlink docs broken link

### PR DESCRIPTION
**Pull request by maikotrindade**
Replace broken link `https://docs.chain.link/docs/testnet-oracles` by `https://docs.chain.link/docs/decentralized-oracles-ethereum-mainnet/#testnets`

### CODE REVIEW

**Review by PatrickAlphaC — APPROVED** [review]
Awesome! Thanks for this PR!

**Comment by PatrickAlphaC** [comment]
Tagging @StephenFluin just to make sure the new pipeline here for external PRs is working as intended

**Comment by PatrickAlphaC** [comment]
Thanks for this PR!

**Comment by maikotrindade** [comment]
Anytime!

**Pull request merged**
